version: '3.8'
services:

  scim-server:
    build: ./okta-scim-server
    ports:
      - 5003:5000
    depends_on:
      - db

  db:
    image: postgres:13-alpine
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data:rw
    ports:
      - 5004:5432
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      DATABASE_HOST: "0.0.0.0"
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: scim  

  ngrok:
    image: ngrok/ngrok:latest
    depends_on:
      - scim-server
    volumes:
      - ./config/ngrok.yml:/var/lib/ngrok/ngrok.yml:ro
    ports:
      - 5001:4040

  adminer:
    image: adminer:standalone
    restart: always
    depends_on: 
      - db
    ports:
      - 5002:8080
